name: Terraform Validate & Plan Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  terraform-validate-plan-vpc-vpc:
    name: Validate and Plan Terraform vpc_management
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: vpc_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform vpc_management
        run: |
          cd vpc_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-subnet:
    name: Validate and Plan Terraform subnet_management
    needs: terraform-validate-plan-vpc-vpc
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: subnet_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform subnet_management
        run: |
          cd subnet_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-igw:
    name: Validate and Plan Terraform igw_management
    needs: terraform-validate-plan-vpc-subnet
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: igw_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform igw_management
        run: |
          cd igw_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-eip:
    name: Validate and Plan Terraform eip_management
    needs: terraform-validate-plan-vpc-igw
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: eip_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform eip_management
        run: |
          cd eip_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-nat-gateway:
    name: Validate and Plan Terraform nat_gateway_management
    needs: terraform-validate-plan-vpc-eip
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: nat_gateway_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform nat_gateway_management
        run: |
          cd nat_gateway_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-route-table:
    name: Validate and Plan Terraform route_table_management
    needs: terraform-validate-plan-vpc-nat-gateway
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: route_table_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform route_table_management
        run: |
          cd route_table_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-route-table-route:
    name: Validate and Plan Terraform route_table_route_management
    needs: terraform-validate-plan-vpc-route-table
    uses: ./.github/workflows/common-steps.yml
    with:
      directory: route_table_route_management
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate and Plan Terraform route_table_route_management
        run: |
          cd route_table_route_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars