name: Terraform Destroy Workflow

on:
  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  terraform-destroy-vpc-route-table-route:
    name: Destroy Terraform route_table_route_management
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: route_table_route_management
      - name: Destroy Terraform route_table_route_management
        run: |
          cd route_table_route_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-route-table:
    name: Destroy Terraform route_table_management
    needs: terraform-destroy-vpc-route-table-route
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: route_table_management
      - name: Destroy Terraform route_table_management
        run: |
          cd route_table_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-nat-gateway:
    name: Destroy Terraform nat_gateway_management
    needs: terraform-destroy-vpc-route-table
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: nat_gateway_management
      - name: Destroy Terraform nat_gateway_management
        run: |
          cd nat_gateway_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-eip:
    name: Destroy Terraform eip_management
    needs: terraform-destroy-vpc-nat-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: eip_management
      - name: Destroy Terraform eip_management
        run: |
          cd eip_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-igw:
    name: Destroy Terraform igw_management
    needs: terraform-destroy-vpc-eip
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: igw_management
      - name: Destroy Terraform igw_management
        run: |
          cd igw_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-subnet:
    name: Destroy Terraform subnet_management
    needs: terraform-destroy-vpc-igw
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: subnet_management
      - name: Destroy Terraform subnet_management
        run: |
          cd subnet_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars

  terraform-destroy-vpc-vpc:
    name: Destroy Terraform vpc_management
    needs: terraform-destroy-vpc-subnet
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/workflows/common-steps.yml
        with:
          directory: vpc_management
      - name: Destroy Terraform vpc_management
        run: |
          cd vpc_management/terraform
          terraform destroy -auto-approve -var-file=../variables/terraform.tfvars
