name: Terraform Validate & Plan Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-validate-plan-vpc-vpc:
    name: Validate and Plan Terraform vpc_management
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: vpc_management
      - name: Validate and Plan Terraform vpc_management
        run: |
          cd vpc_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-subnet:
    name: Validate and Plan Terraform subnet_management
    needs: terraform-validate-plan-vpc-vpc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: subnet_management
      - name: Validate and Plan Terraform subnet_management
        run: |
          cd subnet_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-igw:
    name: Validate and Plan Terraform igw_management
    needs: terraform-validate-plan-vpc-subnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: igw_management
      - name: Validate and Plan Terraform igw_management
        run: |
          cd igw_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-eip:
    name: Validate and Plan Terraform eip_management
    needs: terraform-validate-plan-vpc-igw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: eip_management
      - name: Validate and Plan Terraform eip_management
        run: |
          cd eip_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-nat-gateway:
    name: Validate and Plan Terraform nat_gateway_management
    needs: terraform-validate-plan-vpc-eip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: nat_gateway_management
      - name: Validate and Plan Terraform nat_gateway_management
        run: |
          cd nat_gateway_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-route-table:
    name: Validate and Plan Terraform route_table_management
    needs: terraform-validate-plan-vpc-nat-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: route_table_management
      - name: Validate and Plan Terraform route_table_management
        run: |
          cd route_table_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-validate-plan-vpc-route-table-route:
    name: Validate and Plan Terraform route_table_route_management
    needs: terraform-validate-plan-vpc-route-table
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Steps
        uses: ./.github/actions/common-steps
        with:
          directory: route_table_route_management
      - name: Validate and Plan Terraform route_table_route_management
        run: |
          cd route_table_route_management/terraform
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars
